services:
  dns_adblocker:
    image: dns:latest
    ports:
      - "53:53/udp"
    restart: unless-stopped
    volumes:
      - ./data/blocklist.txt:/app/blocklist.txt
      - ./data/blocked_domains.log:/app/blocked_domains.log
    cap_add:
      - NET_BIND_SERVICE


